### ISSUE TITLE
ObligationId not accessible

### ISSUE THREAD

**Issue by frelibert** [wso2/balana#12]
The following private fields do not have a getter which makes them inaccessible from the java object.
org.wso2.balana.xacml2.Obligation.obligationId
org.wso2.balana.xacml3.Obligation.obligationId

Unless this is done on purpose (why would that be?), you should add a getter for the URI.

**Comment by mefarazath** [comment]
Agreed. Will add this with our next release.

Already we have a PR https://github.com/wso2/balana/pull/41 for one of the classes. Why don't you shoot a PR for the other one :wink:

**Comment by mefarazath** [comment]
Fixed with https://github.com/wso2/balana/pull/41

**Comment by bergerst** [comment]
Please close this issue.
