### ISSUE TITLE
AttributeFinder not called for some categories

### ISSUE THREAD

**Issue by chrert** [wso2/balana#14]
I'm facing a strange problem where my AttributeFinder doesn't get called for some attributes.
I have many different categories in my policies, all of the form `some:path:describing:where:to:find:the:attribue`. It seems random to me which categories will be accepted and which not. For example, `test:auth` will but `test:auth1` and `test:auth:something` will not.

My AttributeFinder does not override `getSupportedIds()` and `getSupportedCategories()`. The doc says, that it will be responsible for any category/id pair in that case. Btw: Are those methods really necessary? It seems that they are not called during an evaluation...

Am I doing something wrong here?

**Comment by chrert** [comment]
Seems like AttributeFinder will only be called for attributes of categories which are within the request. Is this intentional?

**Comment by mefarazath** [comment]
No, it is not the expected behaviour according to the XACML spec. Thanks for reporting this.

fixed with https://github.com/wso2/balana/pull/46
