### ISSUE TITLE
Null reference exception when using general bag functions with custom data types.

### ISSUE THREAD

**Issue by mdrozdo** [wso2/balana#144]
**Description:**
If Balana is configured with a custom data type and a bag function operating on it (i.e. registered using the `public GeneralBagFunction(String functionName, String datatype, String functionType)` constructor), the code throws NullReferenceException from the `GeneralBagFunction.returnsBag()` function.

**Affected Product Version:**
1.2.5

**Steps to reproduce:**
Register a custom datatype e.g.:
```Java
AttributeFactory sattr = StandardAttributeFactory.getNewFactory();
sattr.addDatatype(GeometryAttribute.identifier, new GeometryAttributeProxy());
Balana.getInstance().setAttributeFactory(sattr);
```
and register an associated bag function:
```Java
String functionName;
functionName = bagPrefix + BagFunction.NAME_BASE_ONE_AND_ONLY;
factory.addFunction(BagFunction.getOneAndOnlyInstance(functionName, GeometryAttribute.identifier));
```
Then try to evaluate the policy using such function. 

The problem is due to the fact that when using the aforementioned constructor, the paramMap collection is not initialized with the function name, but rather the function type (e.g. "-one-and-only").  Therefore the GeneralBagFunction.returnsBag() should also use function type and not function name.

**Comment by mdrozdo** [comment]
The issue was introduced in https://github.com/wso2/balana/commit/647338610fc689d799af0f3d4e8222947ef42155 due to overriding in GeneralBagFunction:
```Java
    @Override
    public final boolean returnsBag() {

        return getReturnsBag(getFunctionName());
    }
```

I tried removing this override and the tests pass (it should just use the returnsBag field underneath). Is there any reason for this override?

**Comment by senthalan** [comment]
Closing as the PR is merged. Thank you for your valuable contribution.
