### ISSUE TITLE
StackOverflow Exception in PDP.processPolicyReferences 

### ISSUE THREAD

**Issue by stefanthaler** [wso2/balana#2]
you have a PolicySet containing PolicyA and PolicyB (directly, without any references).

Then https://github.com/wso2/balana/blob/master/modules/balana-core/src/main/java/org/wso2/balana/PDP.java#L332 causes a StackOverflow exception, because it calls the policy instead of the children policy.

**Comment by johannnallathamby** [comment]
Created JIRA: https://wso2.org/jira/browse/IDENTITY-2149
