### ISSUE TITLE
No getting started documentation

### ISSUE THREAD

**Issue by ghost** [wso2/balana#20]
Despite the prescene of a documentation `pom`, there does not appear to be any getting started/on-boarding documentation for Balana.

**Comment by ics-brettma** [comment]
Updated

**Comment by b4n4n4p4nd4** [comment]
Is there a work-in-progress for documentation? I've tried what I know and I can't manage to get the documentation pom to actually download anything.

**Comment by haishuiaa** [comment]
How should I begin？

**Comment by bergerst** [comment]
Try starting with the K-Market demo https://github.com/wso2/balana/tree/master/modules/balana-samples/kmarket-trading-sample

**Comment by ale222** [comment]
Do I need to configure somehow the pdp to be able to work with xacml v2.0 or what needs to be done in order to achieve that?

**Comment by ruwanta** [comment]
@ale222 
Balana is a library to evaluate XACML. Yes, you need to embed and create you own PDP or use a PDP which already embeds Balana. 
You can follow simple way to implement your own PDP if you follow "kmarket" sample and then change the logic accordingly.

**Comment by ruwanta** [comment]
I am closing this issue as the README.md in the root contains how to get started with defining and evaluating your own policy with Balana.
