### ISSUE TITLE
VariableReference doesn't implement Evaluatable

### ISSUE THREAD

**Issue by VictorKrapivin** [wso2/balana#24]
Are there any reason that VariableReference doesn't implement Evaluatable?
So I can't use VariableReference tag in Condition tag...

**Comment by dkm199** [comment]
Hi Guys
can any of u answer above question?
I see variable references aren't implemented in conditions as well
**This thing works.**
       ```
 <Condition>
            <Apply FunctionId="urn:oasis:names:tc:xacml:1.0:function:string-equal">
                <AttributeValue DataType="http://www.w3.org/2001/XMLSchema#string">user1</AttributeValue>
                <AttributeValue DataType="http://www.w3.org/2001/XMLSchema#string">user2</AttributeValue>
            </Apply>
        </Condition>

```
**This doesn't work**

```
     <Condition>
            <Apply FunctionId="urn:oasis:names:tc:xacml:1.0:function:string-equal">
                <AttributeDesignator AttributeId="urn:oasis:names:tc:xacml:3.0:subject:user:location" Category="urn:oasis:names:tc:xacml:3.0:subject-category:access-subject" DataType="http://www.w3.org/2001/XMLSchema#string" MustBePresent="true"/>
                <AttributeDesignator AttributeId="urn:oasis:names:tc:xacml:3.0:resource:user:location" Category="urn:oasis:names:tc:xacml:3.0:attribute-category:resource" DataType="http://www.w3.org/2001/XMLSchema#string" MustBePresent="true"/>
            </Apply>
        </Condition>

```

Please let me know if there is alternative way to achieve this inside condition

Thanks

**Comment by dkm199** [comment]
Nevemind, I figured out what I was doing wrong. Below works
`                <Apply FunctionId="urn:oasis:names:tc:xacml:1.0:function:string-equal">
                    <Apply FunctionId="urn:oasis:names:tc:xacml:1.0:function:string-one-and-only">
                        <AttributeDesignator AttributeId="urn:oasis:names:tc:xacml:3.0:resource:user:location" Category="urn:oasis:names:tc:xacml:3.0:attribute-category:resource" DataType="http://www.w3.org/2001/XMLSchema#string" MustBePresent="true"/>
                    </Apply>
                    <Apply FunctionId="urn:oasis:names:tc:xacml:1.0:function:string-one-and-only">
                        <AttributeDesignator AttributeId="urn:oasis:names:tc:xacml:3.0:subject:user:location" Category="urn:oasis:names:tc:xacml:3.0:subject-category:access-subject" DataType="http://www.w3.org/2001/XMLSchema#string" MustBePresent="true"/>
                    </Apply>
                </Apply>`

**Comment by omindu** [comment]
Fixed with https://github.com/wso2/balana/pull/93
