### ISSUE TITLE
REST API

### ISSUE THREAD

**Issue by jainh** [wso2/balana#45]
Hi

What i understand from the documentation and blogs that balana supports PDP part of Xacml authorization stack, Can you provide me how can we use this as a service with Http layer on top of it ? or is there any existing http transport layer supported by it ?

**Comment by mefarazath** [comment]
As part of GSoC 2016, Entitlement Service REST Impelmentation was done. 

Please find the details below,
https://wso2.org/jira/browse/IDENTITY-4985
