### ISSUE TITLE
javax.xml.namespace - Build Error on Java8

### ISSUE THREAD

**Issue by apowers313** [wso2/balana#47]
When building balana, I get the following error:

> [WARNING] Warning building bundle org.wso2.balana:org.wso2.balana.utils:bundle:1.0.6-SNAPSHOT : Did not find matching referal for !javax.xml.namespace
[WARNING] Warning building bundle org.wso2.balana:org.wso2.balana.utils:bundle:1.0.6-SNAPSHOT : Importing packages that are never refered to by any class on the Bundle-Classpath[Jar:dot]: [javax.xml.namespace]
[ERROR] Error building bundle org.wso2.balana:org.wso2.balana.utils:bundle:1.0.6-SNAPSHOT : Unresolved references to [javax.xml] by class(es) on the Bundle-Classpath[Jar:dot]: [org/wso2/balana/utils/Utils.class]
[ERROR] Error(s) found in bundle configuration

Is that a known issue?

**Comment by b4n4n4p4nd4** [comment]
I can't say if it's a known issue, but I'm pretty sure I've run into that before. If I'm not mistaken, it's related to a dependency on xerces. If you download xerces and its api jar to your classpath, I think the problem goes away. Worth a shot to confirm?

**Comment by apowers313** [comment]
Grabbed the [latest xerces jar files](http://apache.mesi.com.ar//xerces/j/binaries/Xerces-J-bin.2.11.0.tar.gz) and added them to my `CLASSPATH`, but still getting the same error.

Any other ideas?

**Comment by mefarazath** [comment]
@apowers313 what is the Java version you are trying to build this on? 
If it is Java8 I encountered the same and created a JIRA[1] to track and fix this.

[1] https://wso2.org/jira/browse/IDENTITY-5295

**Comment by apowers313** [comment]
Well, I guess that explains it...

> java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

Should we close this out, or leave it open for others to see until a fix is in place?

**Comment by mefarazath** [comment]
Let's keep it open. May be edit the issue heading to say Build Error on Java8.

**Comment by mefarazath** [comment]
Fixed with https://github.com/wso2/balana/pull/51

**Comment by mefarazath** [comment]
@apowers313 you should be able to build Balana on Java 8 now.

**Comment by apowers313** [comment]
Confirmed the fix, thanks again.
