### ISSUE TITLE
Hello, I want to use this balana engine for researching on XACML. 

### ISSUE THREAD

**Issue by GichanLee** [wso2/balana#48]
But It has no description about getting started.
can you help me to do?
I want to put my XACML policy in engine and get the result simply.
Thanks!

**Comment by b4n4n4p4nd4** [comment]
I used this to get started. It gives a reasonably functional starting point where you can dump the sample policies into a local path ./resources/ and get a confirmed throughput from java submitting a constructed string into balana and printing out the output. After that, it's much easier to modify the sample to make it become what you need instead of building the balana interaction from scratch.

https://svn.wso2.org/repos/wso2/trunk/commons/balana/modules/balana-samples/kmarket-trading-sample/src/main/java/org/wso2/balana/samples/kmarket/trading/

**Comment by GichanLee** [comment]
@b4n4n4p4nd4 I'm so sorry, I can't understand your help. where is './resources'? i just found balana-samples/kmarket-trading-sample then run 'run.bat', but didn't work.

**Comment by b4n4n4p4nd4** [comment]
./resources is a relative path from the root folder of the classpath that you're running from. It won't exist unless you create it, but if you look int the code for the kmarket demo, it sets the load folder to that location, so you can just change that folder in the code and it'll look anywhere you like for the policy xml files. The sample doesn't appear to do much in the way of error trapping for bad input, so you have to run it from an interactive command prompt in order to ensure it receives correctly formatted inputs.

**Comment by mefarazath** [comment]
Hi @GichanLee,

To get started you can refer to the sample at [1]. You need to build the samples module using maven. Refer to the README for details on running the sample. And also use [2] as a comprehensive reference XACML and Balana.

[1]  https://github.com/wso2/balana/tree/master/modules/balana-samples
[2]  http://xacmlinfo.org/category/xacml-samples/

**Comment by GichanLee** [comment]
Thanks a lot! I will attempt to do that with your guide.

**Comment by b4n4n4p4nd4** [comment]
You have to integrate the Balana utils into your source environment or classpath. You can get the source from here:

https://github.com/wso2/balana/tree/master/modules/balana-utils/src/main/java/org/wso2/balana/utils

Put everything under that link into the org/wso2/balana/utils folder.

**Comment by GichanLee** [comment]
@b4n4n4p4nd4 I'm so sorry about my shortage..T^T
already I have it. I pulled up all things on the github and made maven project.
my process was 
1. making maven project by pulling up github in intellij. 2. going into balana-samples/K-trade.... 3. make 4. going to ./target folder 5. trying to play with K-trade... but failed with error I said. run "run.sh" also failed. (interactive console isn't supported in intellij -> so, ah, I have to make this with terminal!) /// 7. mvn compile with terminal 8. trying to do it as 5. 9. error with "Could not find or load....." 
I totally agree that I'm real novice.. always being thankful to you guys...T^T

**Comment by mefarazath** [comment]
@GichanLee is the sample working now?

**Comment by GichanLee** [comment]
@mefarazath no, It isn't. I commented you with error message i got

**Comment by mefarazath** [comment]
Okay. Here you go,

1. Checkout the balana source
2. Build from the root of the source (Builld on Java7 since there is a known issue in building on Java8)
3. Add this [jar](https://maven.wso2.org/nexus/service/local/repositories/wso2maven2/content/xerces/wso2/xercesImpl/2.8.1.wso2v2/xercesImpl-2.8.1.wso2v2.jar) to lib folder of the sample you are trying out.
4. use sh run.sh or run.bat (if you are on windows)
5. You should see something like below,


```
 farazath  ~/IS/balana/modules/balana-samples/kmarket-trading-sample   master  sh run.sh

K-Market is on-line trading company. They have implemented some access control over the on-line trading using XACML policies. K-Martket has separated their customers in to three groups and has put limit on on-line buying items.


You can select one of following item for your shopping chart : 

[1] Food	[2] Drink	[3] Fruit	[4] Liquor	 [5] Medicine
Enter User name : alice
Enter Product Id : 2
Enter No of Products : 5

Total Amount is  : 25


======================== XACML Request ====================
<Request xmlns="urn:oasis:names:tc:xacml:3.0:core:schema:wd-17" CombinedDecision="false" ReturnPolicyIdList="false">
<Attributes Category="urn:oasis:names:tc:xacml:3.0:attribute-category:action">
<Attribute AttributeId="urn:oasis:names:tc:xacml:1.0:action:action-id" IncludeInResult="false">
<AttributeValue DataType="http://www.w3.org/2001/XMLSchema#string">buy</AttributeValue>
</Attribute>
</Attributes>
<Attributes Category="urn:oasis:names:tc:xacml:1.0:subject-category:access-subject">
<Attribute AttributeId="urn:oasis:names:tc:xacml:1.0:subject:subject-id" IncludeInResult="false">
<AttributeValue DataType="http://www.w3.org/2001/XMLSchema#string">alice</AttributeValue>
</Attribute>
</Attributes>
<Attributes Category="urn:oasis:names:tc:xacml:3.0:attribute-category:resource">
<Attribute AttributeId="urn:oasis:names:tc:xacml:1.0:resource:resource-id" IncludeInResult="false">
<AttributeValue DataType="http://www.w3.org/2001/XMLSchema#string">Drink</AttributeValue>
</Attribute>
</Attributes>
<Attributes Category="http://kmarket.com/category">
<Attribute AttributeId="http://kmarket.com/id/amount" IncludeInResult="false">
<AttributeValue DataType="http://www.w3.org/2001/XMLSchema#integer">5</AttributeValue>
</Attribute>
<Attribute AttributeId="http://kmarket.com/id/totalAmount" IncludeInResult="false">
<AttributeValue DataType="http://www.w3.org/2001/XMLSchema#integer">25</AttributeValue>
</Attribute>
</Attributes>
</Request>
===========================================================

======================== XACML Response ===================
<Response xmlns="urn:oasis:names:tc:xacml:3.0:core:schema:wd-17"><Result><Decision>Permit</Decision><Status><StatusCode Value="urn:oasis:names:tc:xacml:1.0:status:ok"/></Status></Result></Response>
===========================================================

alice is authorized to perform this purchase
```

**Comment by GichanLee** [comment]
@mefarazath without ide, just with terminal right?

**Comment by mefarazath** [comment]
yeah simply try it with the terminal.

**Comment by GichanLee** [comment]
@mefarazath
<img width="1195" alt="2016-11-15 11 18 45" src="https://cloud.githubusercontent.com/assets/14211395/20290746/4bc8671c-ab25-11e6-886a-80ac53dff0d1.png">
It's locale Korean, but It said that "Could not find or load base(fundamental) class org.wso2~.

**Comment by mefarazath** [comment]
can you run mvn clean install on the root of the source. And then add this [jar](https://maven.wso2.org/nexus/service/local/repositories/atlassian-developer-site/content/apache-xerces/xercesImpl/2.9.1/xercesImpl-2.9.1.jar) to lib of any sample and try to run it? 

Remove the xercesImpl-2.8.1.wso2v2 jar.

**Comment by GichanLee** [comment]
@mefarazath oh... I love you... It works!! Thanks a lot!!! If I wanna do scratch with it, I can just change policies in ./resources right? ah....... I tried to run this for 2 weeks.. Thank you so much.
<img width="1196" alt="2016-11-15 12 21 22" src="https://cloud.githubusercontent.com/assets/14211395/20292074/1cf2cfe6-ab2e-11e6-83a3-3ebe021f56ea.png">
<img width="1208" alt="2016-11-15 12 21 52" src="https://cloud.githubusercontent.com/assets/14211395/20292078/1ec46bd6-ab2e-11e6-89fb-dc6ca102ee9f.png">

**Comment by mefarazath** [comment]
Great!!!! Play around with the other samples as well. Each sample covers a different aspect of XACML. Refer http://xacmlinfo.org/category/xacml-samples/ as needed.

**Comment by Habbeb** [comment]
Hi mefarazath,

how can I use balana without maven, I want to use balana in simple applications

thank you in advance
