### ISSUE TITLE
encode() method of PolicySet misses xml namespace

### ISSUE THREAD

**Issue by pengshuai2010** [wso2/balana#55]
Compared to the encode() method of Policy, encode() method of PolicySet doesn't include `"xmlns= " + metaData.getXACMLIdentifier()` . Since the version id of XACML is in the xml namespace, there's no information about version id in the encoded PolicySet node. 

If we use the resulted string to  load a policy, because there's no information about version id, balana will treat it as xacml version 2.0 by default instead of the correct version.

**Comment by mefarazath** [comment]
Hmm, the PolicySet needs to be fixed. But in the encoded String don't the Policy Elements within the PolicySet contain the correct XACML version?

**Comment by pengshuai2010** [comment]
Yes, in the encoded string, the Policy elements have the correct XACML version number. 

But in my code I need to parse the encoded string as XML document, traverse and modify the DOM, then load it back as a PolicySet object.  Because there's no XACML version number, the Target of the PolicySet will by default has a XACML version number of 2.0, causing trouble for me.

**Comment by mefarazath** [comment]
Yup seems like a legit concern. Will you be able to send a PR with the fix? :wink: 
We could fix this in the next release of Balana.

**Comment by bergerst** [comment]
I've added a PR with the fix for this issue and a few unreported ones I've found.

**Comment by bergerst** [comment]
Sorry for the flood of references in commits. I had to do multiple commits and merge them for this fix.
