### ISSUE TITLE
Repo to get balana from 

### ISSUE THREAD

**Issue by dkm199** [wso2/balana#69]
Hi Guys,
I plan to use balana as a dependency to one of my modules. Is it correct way to include it
// https://mvnrepository.com/artifact/org.wso2.balana/org.wso2.balana
libraryDependencies += "org.wso2.balana" % "org.wso2.balana" % "1.0.0-wso2v7"
as shown in the link below
https://mvnrepository.com/artifact/org.wso2.balana/org.wso2.balana/1.0.0-wso2v7
?
But that seems to have released on 2013.  And here(https://github.com/wso2/balana/releases/tag/v1.1.3) there is version 1.1.3, which seems very recent. But its not hosted in maven?

Please let me know if there are instructions somewhere. thanks

**Comment by bergerst** [comment]
It's this one here http://maven.wso2.org/nexus/content/repositories/releases/

With the balana jars located at http://maven.wso2.org/nexus/content/repositories/releases/org/wso2/balana/ .

**Comment by dkm199** [comment]
thanks

**Comment by mefarazath** [comment]
You can also use https://maven.wso2.org/nexus/#welcome to check dependency information related to WSO2 artifacts.
