### ISSUE TITLE
No possibility to change the root PolicyCombiningAlgorithm

### ISSUE THREAD

**Issue by stefan-ka** [wso2/balana#70]
Hi

I am using Balana as you do it in your samples with the FileBasedPolicyFinderModule (https://github.com/wso2/balana/blob/master/modules/balana-core/src/main/java/org/wso2/balana/finder/impl/FileBasedPolicyFinderModule.java) to find my policy files. But the problem is that the policy combining algorithm is hard coded there. (deny-overrides algorithm) 

See https://github.com/wso2/balana/blob/master/modules/balana-core/src/main/java/org/wso2/balana/finder/impl/FileBasedPolicyFinderModule.java on line 92: 
combiningAlg = new DenyOverridesPolicyAlg(); 

I don't see any possibilities to change that. How can I define the combining algorithm if I have multiple policies (multiple XACML files inside the configured folder)? I know that I can use PolicySet's and define the algorithm there, but then I have to put all my policies into a single file. If I use separate files for the policies and create a PolicySet with Policy-References, it still uses the default DenyOverridesPolicyAlg.

Do I miss something here? Any ideas?

**Comment by bergerst** [comment]
You can write your own PolicyFinderModule where you can change the combining algorithm during the runtime.

The FileBasedPolicyFinderModule provided in the project is only included to have one for the demos. In the Identity Server project this module is used https://github.com/wso2-attic/carbon-identity/blob/master/components/entitlement/org.wso2.carbon.identity.entitlement/src/main/java/org/wso2/carbon/identity/entitlement/policy/finder/CarbonPolicyFinder.java

In my project I am using a self-implemented PolicyFinderModule for storing policies in a database. The combining algorithm is set in the constructor and in a setter.

**Comment by stefan-ka** [comment]
I understand, thank you for your answer. Then I have to implement my own one.

Since it is located in the "core", and I thought that reading policies from files (File-based) might be some kind of a "common scenario", I believed that this is a default implementation. If it is only for demo's, it is maybe located at the wrong place.
