### ISSUE TITLE
XACML3 Result is not XSD compliant

### ISSUE THREAD

**Issue by hanndecl** [wso2/balana#73]
**Description:**
When balana is generating a XACML 3.0 it is not XSD compliant. The element order should be 
Decision, Status , Obligations, AssociatedAdvise, Attributes and PolicyIdentifierList. Balana puts the Attributes after the PolicyIdentifierList.

**Affected Product Version:**
Latest release and snapshot

**Steps to reproduce:**
Validate a full blown XACML Response through an XML validator.

**Comment by mefarazath** [comment]
@hanndecl Thanks for Reporting the issue. Would you happen to have a complete XACML 3.0 Response generated by Balana that you reproduced this issue?

If you do then add it as a comment. That would be helpful.

**Comment by hanndecl** [comment]
FYI: I'm preparing a Pull request with a patch and a junit test to illustrate the problem

**Comment by hanndecl** [comment]
see pull request https://github.com/wso2/balana/pull/74

**Comment by omindu** [comment]
Merged with da916b398f513c05d0c45e423dc183052f0ddcda
